#spring.application.name=supplyFlow
#spring.datasource.url=jdbc:mysql://localhost/supplyFlow
#spring.datasource.username=root
#spring.datasource.password=Reda@reda55
#spring.datasource.tomcat.max-wait=10000
#spring.datasource.tomcat.max-active=500
#spring.datasource.tomcat.test-on-borrow=true



# test
# H2 Database Settings
spring.datasource.url=jdbc:h2:mem:supplyflow
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# This allows you to see the database in your browser
spring.h2.console.enabled=true

# Create the tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=create-drop